name: CraftingAndStats
version: ${project.version}
main: me.pioula111.craftingandstats.CraftingAndStats
api-version: 1.16
authors: [ pioula111 ]
description: Crafting and Stats and fighting

commands:
  nowareceptura:
    description: nowareceptura
    usage: Error
    permission: Operator
  nowycrafting:
    description: nowycrafting
    usage: Error
    permission: Operator
  nowyfach:
    description: nowyfach
    usage: Error
    permission: Operator
  postawcrafting:
    description: postawcrafting
    usage: Error
    permission: Operator
  destroyer:
    description: destroyer
    usage: Error
    permission: Operator
  wytworzprzedmiot:
    description: wytworzprzedmiot
    usage: Error
  stworzitem:
    description: stworzitem
    usage: Error
    permission: Operator
  rzemieslniczy:
    description: rzemieslniczy
    usage: Error
    permission: Operator
  zywnosc:
    description: zywnosc
    usage: Error
    permission: Operator
  inne:
    description: zywnosc
    usage: Error
    permission: Operator
  bron:
    description: bron
    usage: Error
    permission: Operator
  jednoreczna:
    description: jednoreczna
    usage: Error
    permission: Operator
  dwureczna:
    description: dwureczna
    usage: Error
    permission: Operator
  dlugodystansowa:
    description: dlugodystansowa
    usage: Error
    permission: Operator
  dmg:
    description: dmg
    usage: Error
    permission: Operator
  zrecznosc:
    description: zrecznosc
    usage: Error
    permission: Operator
  sila:
    description: sila
    usage: Error
    permission: Operator
  statystyka:
    description: statystyka
    usage: Error
    permission: Operator
  brak:
    description: brak
    usage: Error
    permission: Operator
  wzmocnienie:
    description: wzmocnienie
    usage: Error
    permission: Operator
  obrona:
    description: obrona
    usage: Error
    permission: Operator
  pancerz:
    description: pancerz
    usage: Error
    permission: Operator
  narzedzia:
    description: narzedzia
    usage: Error
    permission: Operator
  kilof:
    description: kilof
    usage: Error
    permission: Operator
  kosa:
    description: kosa
    usage: Error
    permission: Operator
  sierp:
    description: sierp
    usage: Error
    permission: Operator
  topor:
    description: topor
    usage: Error
    permission: Operator
  wedka:
    description: wedka
    usage: Error
    permission: Operator
  napoj:
    description: napoj
    usage: Error
    permission: Operator
  lingering:
    description: lingering
    usage: Error
    permission: Operator
  splash:
    description: splash
    usage: Error
    permission: Operator
  zwykly:
    description: zwykly
    usage: Error
    permission: Operator
  efekty:
    description: efekty
    usage: Error
    permission: Operator
  kolornapoju:
    description: kolornapoju
    usage: Error
    permission: Operator
  przerwijrobienieitemu:
    description: przerwijrobienieitemu
    usage: Error
    permission: Operator
  craftingi:
    description: craftingi
    usage: Error
    permission: Operator
  fachy:
    description: fachy
    usage: Error
    permission: Operator
  receptury:
    description: receptury
    usage: Error
    permission: Operator
  test:
    description: test
    usage: Error
    permission: Operator
