name: CraftingAndStats
version: ${project.version}
main: me.pioula111.craftingandstats.CraftingAndStats
api-version: 1.16
authors: [ pioula111 ]
description: Crafting and Stats and fighting

commands:
  stworzitem:
    description: stworzitem
    usage: Error
    permission: Operator
  handcraft:
    description: rzemieslniczy
    usage: Error
    permission: Operator
  food:
    description: zywnosc
    usage: Error
    permission: Operator
  others:
    description: zywnosc
    usage: Error
    permission: Operator
  weapon:
    description: bron
    usage: Error
    permission: Operator
  one_handed:
    description: jednoreczna
    usage: Error
    permission: Operator
  two_handed:
    description: dwureczna
    usage: Error
    permission: Operator
  long_distance:
    description: dlugodystansowa
    usage: Error
    permission: Operator
  dmg:
    description: dmg
    usage: Error
    permission: Operator
  dexterity:
    description: zrecznosc
    usage: Error
    permission: Operator
  strength:
    description: sila
    usage: Error
    permission: Operator
  statystyka:
    description: statystyka
    usage: Error
    permission: Operator
  none:
    description: brak
    usage: Error
    permission: Operator
  upgrade:
    description: wzmocnienie
    usage: Error
    permission: Operator
  obrona:
    description: obrona
    usage: Error
    permission: Operator
  armor:
    description: pancerz
    usage: Error
    permission: Operator
  tool:
    description: narzedzia
    usage: Error
    permission: Operator
  pickaxe:
    description: kilof
    usage: Error
    permission: Operator
  scythe:
    description: kosa
    usage: Error
    permission: Operator
  sickle:
    description: sierp
    usage: Error
    permission: Operator
  axe:
    description: topor
    usage: Error
    permission: Operator
  fishing_rod:
    description: wedka
    usage: Error
    permission: Operator
  drink:
    description: napoj
    usage: Error
    permission: Operator
  efekty:
    description: efekty
    usage: Error
    permission: Operator
  kolornapoju:
    description: kolornapoju
    usage: Error
    permission: Operator
  przerwijrobienieitemu:
    description: przerwijrobienieitemu
    usage: Error
    permission: Operator
  listaefektow:
    description: listaefektow
    usage: Error
    permission: Operator
  staty:
    description: staty
    usage: Error
