name: CraftingAndStats
version: ${project.version}
main: me.pioula111.craftingandstats.CraftingAndStats
api-version: 1.16
authors: [ pioula111 ]
description: Crafting and Stats and fighting

commands:
  nowareceptura:
    description: nowareceptura
    usage: Error
    permission: Operator
  nowycrafting:
    description: nowycrafting
    usage: Error
    permission: Operator
  nowyfach:
    description: nowyfach
    usage: Error
    permission: Operator
  postawcrafting:
    description: postawcrafting
    usage: Error
    permission: Operator
  destroyer:
    description: destroyer
    usage: Error
    permission: Operator
  wytworzprzedmiot:
    description: wytworzprzedmiot
    usage: Error
  stworzitem:
    description: stworzitem
    usage: Error
    permission: Operator
  rzemieslniczy:
    description: rzemieslniczy
    usage: Error
    permission: Operator
  zywnosc:
    description: zywnosc
    usage: Error
    permission: Operator
  inne:
    description: zywnosc
    usage: Error
    permission: Operator
  bron:
    description: bron
    usage: Error
    permission: Operator
  jednoreczna:
    description: jednoreczna
    usage: Error
    permission: Operator
  dwureczna:
    description: dwureczna
    usage: Error
    permission: Operator
  dlugodystansowa:
    description: dlugodystansowa
    usage: Error
    permission: Operator
  dmg:
    description: dmg
    usage: Error
    permission: Operator
  zrecznosc:
    description: zrecznosc
    usage: Error
    permission: Operator
  sila:
    description: sila
    usage: Error
    permission: Operator
  statystyka:
    description: statystyka
    usage: Error
    permission: Operator
  brak:
    description: brak
    usage: Error
    permission: Operator
  wzmocnienie:
    description: wzmocnienie
    usage: Error
    permission: Operator